# Generated by Django 5.0.6 on 2024-05-24 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_quntity_orderitem_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='Product',
            new_name='product',
        ),
    ]
