# Generated by Django 5.0.6 on 2024-06-02 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_transaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
